Sub CATMain()

'''''''''''''''''
'CATIA气路cgr拆分整理
'1.拆分VLV
'2.添加了程序运行时间显示
'3.随机着色处理

'暂不考虑，仅作为气路评审使用
'1.自动打开处理后关闭，批量处理
Dim t1 As Date

t1 = Timer

Dim productDocument1 As Document
Set productDocument1 = CATIA.ActiveDocument

Dim product1 As Product
Set product1 = productDocument1.Product

Dim products1 As Products
Set products1 = product1.Products

Dim dic As Object
Set dic = CreateObject("scripting.dictionary")

Dim productCut As Product
Dim PartNumber As String
Dim splitText As String
Dim arr As Variant
Dim VLVText As String

Dim i As Integer
For i = products1.Count To 1 Step -1
    Set productCut = products1.Item(i)
    productCut.Name = productCut.PartNumber & ".1"
    
    PartNumber = UCase(productCut.PartNumber)
    If Len(PartNumber) > 10 Then '利用长度限制二次操作
        If InStr(PartNumber, "CYL") <> 0 Then
        
            '防错，"-" 与 "_"
            If InStr(PartNumber, "-") <> 0 Then
                PartNumber = VBA.Replace(PartNumber, "-", "_")
            End If
            
            arr = Split(PartNumber, "_")
            splitText = arr(UBound(arr))
            If Len(splitText) > 5 Then
                VLVText = "VLV" & Mid$(splitText, 4, 2)
            Else
                VLVText = "VLV0" & Mid$(splitText, 4, 1)
            End If
        Else
            VLVText = "FIX"
        End If
        
        If Not dic.Exists(VLVText) Then
            dic.Add VLVText, VLVText & ".1"
            Dim productVLV As Product
            Set productVLV = products1.AddNewProduct(VLVText)
        End If
        
        '粘贴板的剪切处理
        Dim selection2
        Set selection2 = productDocument1.Selection
        selection2.Clear
        
        selection2.Add productCut
        selection2.Cut
        
        '粘贴板的粘贴处理
        Dim selection3
        Set selection3 = productDocument1.Selection
        selection3.Clear
        
        Dim productPaste As Product
        Set productPaste = products1.GetItem(dic(VLVText))
        
        selection3.Add productPaste
        selection3.Paste
    End If
    DoEvents
Next i

ReorderGraphTree

'保存文档
'Set productDocument1 = CATIA.ActiveDocument
'
'productDocument1.Save

MsgBox "程序运行结束，请检查，谢谢！" & vbCrLf & "程序运行时间：" & Format$(Timer - t1, "0.00") & "s"

End Sub

Function ReorderGraphTree()

    '剪切排序处理
    Dim productDocument1 As Document
    Set productDocument1 = CATIA.ActiveDocument
    
    Dim product1 As Product
    Set product1 = productDocument1.Product
    
    Dim products1 As Products
    Set products1 = product1.Products
    
    Dim i As Integer
    
    Dim productCut As Product
    
    Dim PdCount As Integer
    PdCount = products1.Count
    
    Dim MInIndex As Integer
    Dim j As Integer
    Dim VLVNUm1 As Integer
    Dim VLVNUm2 As Integer
    
    Dim PartNumber1 As String
    Dim PartNumber2 As String
    
    For i = PdCount To 1 Step -1
        MInIndex = i
        
        PartNumber1 = products1.Item(i).PartNumber
        
        If InStr(PartNumber1, "FIX") = 0 Then
            VLVNUm1 = Int(Mid$(PartNumber1, 4, 2))
            For j = 1 To i - 1
                PartNumber2 = products1.Item(j).PartNumber
                If InStr(PartNumber2, "FIX") = 0 Then
                    VLVNUm2 = Int(Mid$(PartNumber2, 4, 2))
                    If VLVNUm2 < VLVNUm1 Then
                        MInIndex = j
                        VLVNUm1 = VLVNUm2
                    End If
                Else
                    MInIndex = j
                    Exit For
                End If
            Next
        End If
        '粘贴板的剪切处理
        Set productCut = products1.Item(MInIndex)
        Dim selection2 As Selection
        Set selection2 = productDocument1.Selection
        selection2.Clear
        
        selection2.Add productCut
        selection2.Cut
        
        '粘贴板的粘贴处理
        Dim section1 As Selection
        Set section1 = productDocument1.Selection
    
        ' select top product in a CATIA tree
        section1.Clear
        section1.Add product1
        section1.Paste
    Next

End Function

Function AddColor()
    '增加颜色
    '随机数不重复，待添加
    Dim productDocument1 As Document
    Set productDocument1 = CATIA.ActiveDocument
    
    Dim product1 As Product
    Set product1 = productDocument1.Product
    
    Dim products1 As Products
    Set products1 = product1.Products
    
    'RGB颜色控制
    Dim r1 As Long
    Dim g1 As Long
    Dim b1 As Long
    
    '产品当前层级数量
    Dim PdCount As Integer
    PdCount = products1.Count
    
    Dim productAddCol As Product
    '第一个不进行上色
    Dim i As Integer
    For i = 2 To PdCount
    
        Set productAddCol = products1.Item(i)
        
        Dim selection1 As Selection
        Set selection1 = productDocument1.Selection
        
        selection1.Add productAddCol
        
        Dim Obj As Object
        Set Obj = selection1.VisProperties
        
        '随机整数公式为“int（（上限-下限+1）*Rnd+下限）”
        r1 = Int((25 - 1 + 1) * Rnd + 1)
        g1 = Int((25 - 1 + 1) * Rnd + 1)
        b1 = Int((25 - 1 + 1) * Rnd + 1)
        
        Obj.SetRealColor 10 * r1, 10 * b1, 10 * g1, 0
        
        selection1.Clear
    Next
End Function